### ISSUE TITLE
Strip url to get "original image"

### ISSUE THREAD

**Issue by kaitoukid-1412** [gsdukbh/wallpaper#1]
**unStrip**
https://cn.bing.com/th?id=OHR.SpiralAloe_ZH-CN5594814833_UHD.jpg&rf=LaDigue_UHD.jpg&pid=hp&w=3840&h=2160&rs=1&c=4 (790 KB)

**Striped**
`&rf=LaDigue_UHD.jpg&pid=hp&w=3840&h=2160&rs=1&c=4`
https://cn.bing.com/th?id=OHR.SpiralAloe_ZH-CN5594814833_UHD.jpg (2.41 MB)

**Comment by gsdukbh** [comment]
This is for compressed pictures. I use the file name beginning with bing to save it。You can find him in the `images` file directory。
